source 'https://github.com/coodly/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'InsightAdmin' do
    platform :ios, '13.1'

	pod 'CloudInsight', :path => '../'
end
