source 'https://github.com/coodly/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

def insight_pods
  pod 'CloudInsight/Reporting', :path => '../'
  pod 'CloudInsight/Client', :path => '../'
end

target 'InsightAdmin' do
    platform :ios, '13.1'

end

target 'InsightCore' do
    platform :ios, '13.1'
    
    insight_pods
end

target 'InsightUI' do
    platform :ios, '13.1'
    
    insight_pods
end
